/**
 * Markdown 渲染 —— 把 CodeMapReport 渲染成 docs/CODE-MAP.md。
 *
 * 输出 sections:
 *   1. 概览(总文件/LOC/字节/扫描时间)
 *   2. 5 layer 分布(表格 + 占比)
 *   3. 模块清单(每文件 1 行:path / LOC / exports / imports / layer)
 *   4. Top 20 Hot Spots(inbound import 数)
 *   5. Capability Manifest 命中度
 *   6. Orphan 候选(死文件)
 *   7. 错误列表
 */
import type { CodeMapReport, Layer } from './types.js';

const LAYER_LABELS: Record<Layer, string> = {
  L1: 'L1 基础循环 (Base Loop)',
  L2: 'L2 工具 + 技能 (Tools + Skills)',
  L3: 'L3 多 Agent 编排 (Multi-Agent)',
  L4: 'L4 远程协同 (Remote Collaboration)',
  L5: 'L5 持续自主 (Persistent Autonomy)',
  other: '其他 (Other / Utils / Data)',
};

export function renderCodeMap(report: CodeMapReport): string {
  const lines: string[] = [];
  const scan = report.scan;
  // ---- 概览 ----
  lines.push(`# upup 代码地图 (auto-generated by code-archaeology v0.1)`);
  lines.push('');
  lines.push(`> **生成时间**: ${report.generatedAt}  `);
  lines.push(`> **Repo 根**: \`${report.root}\`  `);
  lines.push(`> **扫描文件数**: ${scan.totalFiles}  `);
  lines.push(`> **总 LOC**: ${scan.totalLoc.toLocaleString()}  `);
  lines.push(`> **总字节**: ${(scan.totalBytes / 1024).toFixed(1)} KB`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ---- 5 layer 分布 ----
  lines.push('## 5 Layer 分布');
  lines.push('');
  lines.push('| Layer | Files | LOC | LOC % | Bytes % |');
  lines.push('|------|------|-----|-------|---------|');
  const totalLocAll = report.layers.reduce((a, l) => a + l.totalLoc, 0) || 1;
  const totalBytesAll = scan.totalBytes || 1;
  for (const ls of report.layers) {
    const locPct = (ls.totalLoc / totalLocAll * 100).toFixed(1);
    const bytePct = (ls.totalLoc * 50 / totalBytesAll * 100).toFixed(1); // 粗估
    lines.push(`| ${LAYER_LABELS[ls.layer]} | ${ls.fileCount} | ${ls.totalLoc.toLocaleString()} | ${locPct}% | ${bytePct}% |`);
  }
  lines.push('');

  // ---- 模块清单(top 50 by LOC)----
  lines.push('## 模块清单 (Top 50 by LOC)');
  lines.push('');
  lines.push('| File | LOC | Exports | Imports | Layer |');
  lines.push('|------|-----|---------|---------|-------|');
  const topFiles = [...scan.files].sort((a, b) => b.loc - a.loc).slice(0, 50);
  for (const f of topFiles) {
    const exp = f.exports.length || '-';
    const imp = f.imports.length || '-';
    lines.push(`| \`${f.relPath}\` | ${f.loc} | ${exp} | ${imp} | ${f.layer} |`);
  }
  lines.push('');

  // ---- Top Hot Spots ----
  lines.push(`## Top ${report.hotspots.length} Hot Spots (Most Imported)`);
  lines.push('');
  lines.push('| Rank | File | Inbound | Layer |');
  lines.push('|------|------|---------|-------|');
  report.hotspots.forEach((h, i) => {
    lines.push(`| ${i + 1} | \`${h.relPath}\` | ${h.inboundCount} | ${h.layer} |`);
  });
  lines.push('');

  // ---- Capability Manifest 命中度 ----
  lines.push('## Capability Manifest 命中度');
  lines.push('');
  lines.push('| Group | Title | Matched Files | Prefixes |');
  lines.push('|-------|-------|---------------|----------|');
  for (const c of report.manifestCoverage) {
    const pfx = c.prefixes.map((p) => `\`${p}\``).join(' ');
    lines.push(`| \`${c.groupId}\` | ${c.title} | ${c.matchedFiles} | ${pfx} |`);
  }
  lines.push('');

  // ---- Orphan 候选(top 30)----
  if (report.orphans.length > 0) {
    lines.push(`## Orphan 候选 (${report.orphans.length} 个)`);
    lines.push('');
    lines.push('> 警告:这些文件没有任何 inbound import。可能是 entry point、test fixture、SKILL.md 资源,需人工复核。');
    lines.push('');
    lines.push('| File | Layer | LOC | Reason |');
    lines.push('|------|-------|-----|--------|');
    for (const o of report.orphans.slice(0, 30)) {
      lines.push(`| \`${o.relPath}\` | ${o.layer} | ${o.loc} | ${o.reason} |`);
    }
    if (report.orphans.length > 30) {
      lines.push(`| ... (还有 ${report.orphans.length - 30} 个) | | | |`);
    }
    lines.push('');
  }

  // ---- 错误 ----
  if (scan.errors.length > 0) {
    lines.push(`## 错误 (${scan.errors.length})`);
    lines.push('');
    for (const e of scan.errors) {
      lines.push(`- \`${e.path}\`: ${e.error}`);
    }
    lines.push('');
  }

  // ---- 末尾 ----
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [code-archaeology v0.1] · [Sprint v4-1 of top-tier-investment-claude-code-v4]*`);
  return lines.join('\n');
}
