import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

export type PlatformCronSchedule = { kind: 'at'; at: string } | { kind: 'every'; everyMs: number; anchorMs?: number } | { kind: 'cron'; expr: string; tz?: string };
export type PlatformCronJob = { id: string; name: string; description?: string; enabled: boolean; createdAtMs: number; updatedAtMs: number; schedule: PlatformCronSchedule; payload: { message: string; model?: string; modelProvider?: string }; fulfillment: 'keep' | 'once' | 'ask'; activeHours?: { start: string; end: string; timezone?: string; daysOfWeek?: number[] }; state: { nextRunAtMs?: number; lastRunAtMs?: number; lastRunStatus?: 'ok' | 'error' | 'suppressed'; lastError?: string; lastDurationMs?: number; consecutiveErrors: number; scheduleErrorCount: number } };
type CronStore = { version: 1; jobs: PlatformCronJob[] };

function path(): string { return process.env.UPUP_CRON_STORE?.trim() || join(process.env.UPUP_HOME?.trim() || join(process.env.HOME || homedir(), '.upup'), 'cron', 'jobs.json'); }
async function store(): Promise<CronStore> { if (!existsSync(path())) return { version: 1, jobs: [] }; try { const value: unknown = JSON.parse(await readFile(path(), 'utf8')); return value && typeof value === 'object' && Array.isArray((value as { jobs?: unknown }).jobs) ? value as CronStore : { version: 1, jobs: [] }; } catch { return { version: 1, jobs: [] }; } }
async function save(value: CronStore): Promise<void> { await mkdir(dirname(path()), { recursive: true }); const temporary = `${path()}.${process.pid}.${randomBytes(4).toString('hex')}.tmp`; try { await writeFile(temporary, JSON.stringify(value, null, 2)); await rename(temporary, path()); } catch (error) { await unlink(temporary).catch(() => undefined); throw error; } }
export function nextCronRun(schedule: PlatformCronSchedule, now = Date.now()): number | undefined { if (schedule.kind === 'at') { const target = Date.parse(schedule.at); return Number.isFinite(target) && target > now ? target : undefined; } if (schedule.kind === 'every') { if (!Number.isFinite(schedule.everyMs) || schedule.everyMs < 60_000) return undefined; const anchor = schedule.anchorMs ?? now; const next = anchor + Math.ceil((now - anchor) / schedule.everyMs) * schedule.everyMs; return next <= now ? next + schedule.everyMs : next; } return nextSimpleCronRun(schedule, now); }
function nextSimpleCronRun(schedule: Extract<PlatformCronSchedule, { kind: 'cron' }>, now: number): number | undefined { const fields = schedule.expr.trim().split(/\s+/); if (fields.length !== 5 && fields.length !== 6) return undefined; const [minute, hour, day, month, weekday] = fields.length === 5 ? fields : fields.slice(1); const candidate = new Date(now + 60_000); candidate.setSeconds(0, 0); for (let step = 0; step < 60 * 24 * 366; step += 1) { const values = [candidate.getMinutes(), candidate.getHours(), candidate.getDate(), candidate.getMonth() + 1, candidate.getDay()]; if ([minute, hour, day, month, weekday].every((field, index) => matchesCronField(field!, values[index]!))) return candidate.getTime(); candidate.setTime(candidate.getTime() + 60_000); } return undefined; }
function matchesCronField(field: string, value: number): boolean { if (field === '*') return true; return field.split(',').some((part) => { const [range, stepText] = part.split('/'); const step = stepText ? Number(stepText) : 1; if (!Number.isInteger(step) || step < 1) return false; if (range === '*') return value % step === 0; if (range?.includes('-')) { const [startText, endText] = range.split('-'); const start = Number(startText); const end = Number(endText); return Number.isInteger(start) && Number.isInteger(end) && value >= start && value <= end && (value - start) % step === 0; } const exact = Number(range); return Number.isInteger(exact) && value === exact; }); }
function summary(job: PlatformCronJob): string { const next = job.state.nextRunAtMs ? new Date(job.state.nextRunAtMs).toISOString() : 'none'; return `**${job.name}** (${job.id}) [${job.enabled ? 'enabled' : 'DISABLED'}]\n  Schedule: ${job.schedule.kind === 'cron' ? `${job.schedule.expr}${job.schedule.tz ? ` (${job.schedule.tz})` : ''}` : job.schedule.kind === 'at' ? `one-shot at ${job.schedule.at}` : `every ${Math.round(job.schedule.everyMs / 1000)}s`}\n  Fulfillment: ${job.fulfillment}\n  Next run: ${next}\n  Last run: ${job.state.lastRunAtMs ? new Date(job.state.lastRunAtMs).toISOString() : 'never'} (${job.state.lastRunStatus ?? 'never'})${job.description ? `\n  Description: ${job.description}` : ''}`; }
export interface PlatformCronRunRequest { readonly job: PlatformCronJob; }
export async function platformCron(input: { action: 'list' | 'add' | 'update' | 'remove' | 'run'; name?: string; description?: string; schedule?: PlatformCronSchedule; message?: string; model?: string; modelProvider?: string; fulfillment?: 'keep' | 'once' | 'ask'; jobId?: string; enabled?: boolean }, run?: (request: PlatformCronRunRequest, signal?: AbortSignal) => Promise<void>, signal = new AbortController().signal): Promise<unknown> {
  const current = await store();
  if (input.action === 'list') return current.jobs.length ? current.jobs.map(summary).join('\n\n') : 'No scheduled jobs.';
  if (input.action === 'add') { if (!input.name || !input.schedule || !input.message) return 'Error: name, schedule, and message are required for add.'; const now = Date.now(); const next = nextCronRun(input.schedule, now); if (input.schedule.kind === 'at' && next === undefined) return 'Error: the specified time is in the past or invalid.'; const job: PlatformCronJob = { id: randomBytes(8).toString('hex'), name: input.name, ...(input.description ? { description: input.description } : {}), enabled: true, createdAtMs: now, updatedAtMs: now, schedule: input.schedule, payload: { message: input.message, ...(input.model ? { model: input.model } : {}), ...(input.modelProvider ? { modelProvider: input.modelProvider } : {}) }, fulfillment: input.fulfillment ?? 'keep', state: { nextRunAtMs: next, consecutiveErrors: 0, scheduleErrorCount: 0 } }; current.jobs.push(job); await save(current); return `Created job "${job.name}" (id: ${job.id}, fulfillment: ${job.fulfillment}). Next run: ${next ? new Date(next).toISOString() : 'pending'}`; }
  if (!input.jobId) return `Error: jobId is required for ${input.action}.`;
  const index = current.jobs.findIndex((job) => job.id === input.jobId); if (index < 0) return `Error: job ${input.jobId} not found.`; const job = current.jobs[index]!;
  if (input.action === 'remove') { current.jobs.splice(index, 1); await save(current); return `Removed job "${job.name}" (id: ${job.id}).`; }
  if (input.action === 'run') { if (!run) throw new Error('cron runner capability is unavailable; run is fail-closed'); await run({ job }, signal); return `Job "${job.name}" executed. Status: ${job.state.lastRunStatus ?? 'unknown'}`; }
  if (input.name !== undefined) job.name = input.name; if (input.description !== undefined) job.description = input.description; if (input.schedule !== undefined) { job.schedule = input.schedule; job.state.nextRunAtMs = nextCronRun(input.schedule); job.state.scheduleErrorCount = 0; } if (input.message !== undefined) job.payload.message = input.message; if (input.model !== undefined) job.payload.model = input.model; if (input.modelProvider !== undefined) job.payload.modelProvider = input.modelProvider; if (input.fulfillment !== undefined) job.fulfillment = input.fulfillment; if (input.enabled !== undefined) { job.enabled = input.enabled; if (input.enabled) job.state.nextRunAtMs ??= nextCronRun(job.schedule); } job.updatedAtMs = Date.now(); await save(current); return `Updated job "${job.name}" (id: ${job.id}).`;
}
