import { randomUUID } from 'node:crypto';

export type PlatformTaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
export interface PlatformTask { id: string; name: string; description?: string; status: PlatformTaskStatus; createdAt: string; startedAt?: string; completedAt?: string; result?: string; error?: string; progress?: number; metadata?: Record<string, unknown>; }
export interface PlatformTaskState { version: 1; tasks: PlatformTask[]; }

export function createInitialPlatformTaskState(): PlatformTaskState { return { version: 1, tasks: [] }; }
export function parsePlatformTaskState(value: unknown): PlatformTaskState { if (!value || typeof value !== 'object') return createInitialPlatformTaskState(); const candidate = value as { version?: unknown; tasks?: unknown }; return candidate.version === 1 && Array.isArray(candidate.tasks) ? { version: 1, tasks: candidate.tasks.filter(isTask).map((task) => ({ ...task, ...(task.metadata ? { metadata: { ...task.metadata } } : {}) })) } : createInitialPlatformTaskState(); }
export function createPlatformTask(input: { name: string; description?: string; metadata?: Record<string, unknown> }, now = new Date().toISOString()): PlatformTask { return { id: randomUUID(), name: input.name, ...(input.description ? { description: input.description } : {}), status: 'pending', createdAt: now, ...(input.metadata ? { metadata: input.metadata } : {}) }; }
export function getPlatformTask(state: PlatformTaskState, id: string): PlatformTask | undefined { return state.tasks.find((task) => task.id === id); }
export function listPlatformTasks(state: PlatformTaskState, status?: PlatformTaskStatus): PlatformTask[] { return state.tasks.filter((task) => status === undefined || task.status === status).sort((left, right) => right.createdAt.localeCompare(left.createdAt)); }
export function platformTaskStats(tasks: readonly PlatformTask[]): Record<PlatformTaskStatus | 'total', number> { return { total: tasks.length, pending: tasks.filter((task) => task.status === 'pending').length, running: tasks.filter((task) => task.status === 'running').length, completed: tasks.filter((task) => task.status === 'completed').length, failed: tasks.filter((task) => task.status === 'failed').length, cancelled: tasks.filter((task) => task.status === 'cancelled').length }; }
export function updatePlatformTask(state: PlatformTaskState, id: string, updates: Partial<Pick<PlatformTask, 'progress' | 'result' | 'metadata' | 'status' | 'error'>>, now = new Date().toISOString()): PlatformTask | undefined { const task = getPlatformTask(state, id); if (!task) return undefined; Object.assign(task, updates); if (updates.status === 'running') task.startedAt ??= now; if (updates.status === 'completed' || updates.status === 'failed' || updates.status === 'cancelled') task.completedAt = now; return task; }
function isTask(value: unknown): value is PlatformTask { if (!value || typeof value !== 'object') return false; const task = value as Partial<PlatformTask>; return typeof task.id === 'string' && typeof task.name === 'string' && typeof task.status === 'string' && typeof task.createdAt === 'string'; }
